sudo: required

branches:
  only:
    - main

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t jungmin86/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jungmin86/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "ap-northeast-1"
  app: "docker-react-app-main"
  env: "Dockerreactappmain-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-533405551470"
  bucket_path: "docker-react-app-main"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
